# Generated by Django 5.2.16 on 2026-07-31 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='country',
            field=models.CharField(default='Nigeria', max_length=100),
        ),
    ]
