# Generated by Django 5.2.16 on 2026-08-18 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_property_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive'), ('rented', 'Rented'), ('sold', 'Sold')], default='active', max_length=20),
        ),
    ]
