# Generated by Django 6.1.1 on 2026-09-22 10:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_property_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='savedproperty',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('self_contain', 'Self-Contain'), ('mini_flat', 'Mini Flat'), ('flat', 'Flat'), ('house', 'House'), ('condo', 'Condo'), ('studio', 'Studio'), ('villa', 'Villa'), ('townhouse', 'Townhouse'), ('room', 'Room')], default='apartment', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('property', 'user'), name='unique_property_review_per_user'),
        ),
        migrations.AddConstraint(
            model_name='savedproperty',
            constraint=models.UniqueConstraint(fields=('user', 'property'), name='unique_saved_property_per_user'),
        ),
    ]
